### ISSUE TITLE
Add version detection too for wappalyzer fingerprint database

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/wappalyzergo#3]
- [ ] Include version information
- [x] ~~Include website associted with tech~~

**Comment by dogasantos** [comment]
+1

**Comment by ehsandeep** [comment]
latest version of wappalyzergo now includes version information when available, changes will be reflected in [httpx](https://github.com/projectdiscovery/httpx) upon next release, currently pushed in dev version.
