### ISSUE TITLE
A third of the technologies listed in fingerprints_data.json will never be detected

### ISSUE THREAD

**Issue by stikhun** [projectdiscovery/wappalyzergo#39]
A third of the technologies listed in fingerprints_data.json will never be detected, as the only keys listed there are the technology name and description
examples:
"AddShoppers":{"description": "AddShoppers is the ...
"ECharts":{"description": "ECharts is an open-source...
...
And there are 884 similar technologies, which only add weight to file fingerprints_data.json for nothing, because from original file keys are missing: scriptSrc, dom

P.S.: Apologies for my bad English, I use a translator

**Comment by chrisanderton** [comment]
I think that's because wappalyzergo doesn't support all the fingerprint patterns? I don't see [dom is implemented](https://github.com/projectdiscovery/wappalyzergo/blob/main/cmd/update-fingerprints/main.go#L47).. nor scriptSrc.
