### ISSUE TITLE
Add service's website information to wappalyzer fingerprint database

### ISSUE THREAD

**Issue by shelld3v** [projectdiscovery/wappalyzergo#4]

**Comment by ehsandeep** [comment]
@shelld3v just wanted to confirm if this is different from https://github.com/projectdiscovery/wappalyzergo/issues/3?

**Comment by shelld3v** [comment]
> @shelld3v just wanted to confirm if this is different from #3?

Yes, what I wanted to say is that, when wappalyzer detected a technology, Wordpress for example, it should provide the link to that service (homepage), and `https://wordpress.com` is, in this situation.

**Comment by ehsandeep** [comment]
@shelld3v I've included this information in https://github.com/projectdiscovery/wappalyzergo/issues/3, closing this one it will be handled as part of another issue.

**Comment by ehsandeep** [comment]
@shelld3v this is now added with - https://github.com/projectdiscovery/wappalyzergo/pull/35
