### ISSUE TITLE
Original Wappalyzer project not open source anymore - Fingerprints failed to download

### ISSUE THREAD

**Issue by BBerastegui** [projectdiscovery/wappalyzergo#57]
Hi all!

Pretty recently, the Wappalyzer original project has been made private (see [here](https://twitter.com/elbertalias/status/1694454191266390361)).

Therefore, the fingerprints fail to download from the original repository.

I saw some discussion here: https://news.ycombinator.com/item?id=37236746

And there are several repositories with the latest snapshot.

Should we consider to start maintaining a list of fingerprints inside this same repository using the original one as a baseline?

I just created a repository for myself that I would love to try to maintain with the community if needed: https://github.com/BBerastegui/wappalyzer-fingerprints

From now we can pull from there.

Cheers!

**Comment by Mzack9999** [comment]
@BBerastegui Thanks for opening this issue. The repository still retain the latest valid parsed version of the dataset, correctly the GH action fails to update it as the original one is not available anymore, and it would be a zero-sum value operation parsing always the same version of the dataset, as the outcome would be the existing one. We are evaluating how to proceed, probably a community maintained version would be the best option. I've also opened a new issue at https://github.com/projectdiscovery/wappalyzergo/issues/59 to investigate a more maintainable alternative as editing huge jsons is a very hostic task

**Comment by zlgxzswjy** [comment]
I noticed [enther](https://github.com/enthec/webappanalyzer) declaring,"This project is a continuation of the ionic Wappalyzer."

**Comment by Mzack9999** [comment]
Superseded by https://github.com/projectdiscovery/wappalyzergo/issues/59
