### ISSUE TITLE
Version regex is nill causing invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by LeDuySon** [projectdiscovery/wappalyzergo#93]
Hi projectdiscovery team, thank you guys for the great tool. I want to report the issue that caused this error "invalid memory address or nil pointer dereference". I have debugged and figured out that the VersionRegex is Nil, the error happened in "github.com/projectdiscovery/wappalyzergo.(*VersionRegex).MatchString"

![image](https://github.com/projectdiscovery/wappalyzergo/assets/33374938/f563ac50-c83a-4d62-abb3-3ff119c8d3ad)

You guys can reproduce the error using below code! 
```
package main

import (
	"fmt"
	"io"
	"log"
	"net/http"

	wappalyzer "github.com/projectdiscovery/wappalyzergo"
)

func main() {
	resp, err := http.DefaultClient.Get("https://samchicks.com")
	if err != nil {
		log.Fatal(err)
	}
	data, _ := io.ReadAll(resp.Body) // Ignoring error for example

	wappalyzerClient, err := wappalyzer.New()
	fingerprints := wappalyzerClient.Fingerprint(resp.Header, data)
	fmt.Printf("%v\n", fingerprints)

	// Output: map[Acquia Cloud Platform:{} Amazon EC2:{} Apache:{} Cloudflare:{} Drupal:{} PHP:{} Percona:{} React:{} Varnish:{}]
}
```

**Comment by Ice3man543** [comment]
@LeDuySon I have linked #94 which solves the panic and adds improve handling for regexes etc

```
map[Bootstrap:{} Botble CMS:6.7.2:{} Google Analytics:{} Laravel:{} MySQL:{} Nginx:1.18.0:{} PHP:{} Popper:{} Skilldo:6.7.2:{} Slick:{} Ubuntu:{} jQuery:{}]
```

Example Output above
